// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	dto "marcceljanara/wallet-ledger-service/internal/dto"
	model "marcceljanara/wallet-ledger-service/internal/model"

	uuid "github.com/google/uuid"
)

// NotificationService is an autogenerated mock type for the NotificationService type
type NotificationService struct {
	mock.Mock
}

// CreateAndPushNotification provides a mock function with given fields: ctx, userID, title, message
func (_m *NotificationService) CreateAndPushNotification(ctx context.Context, userID uuid.UUID, title string, message string) (*model.Notification, error) {
	ret := _m.Called(ctx, userID, title, message)

	if len(ret) == 0 {
		panic("no return value specified for CreateAndPushNotification")
	}

	var r0 *model.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (*model.Notification, error)); ok {
		return rf(ctx, userID, title, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) *model.Notification); ok {
		r0 = rf(ctx, userID, title, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, userID, title, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNotifications provides a mock function with given fields: ctx, userID, pagination
func (_m *NotificationService) GetNotifications(ctx context.Context, userID uuid.UUID, pagination dto.PaginationRequest) (*dto.NotificationListResponse, error) {
	ret := _m.Called(ctx, userID, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetNotifications")
	}

	var r0 *dto.NotificationListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.PaginationRequest) (*dto.NotificationListResponse, error)); ok {
		return rf(ctx, userID, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.PaginationRequest) *dto.NotificationListResponse); ok {
		r0 = rf(ctx, userID, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.NotificationListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.PaginationRequest) error); ok {
		r1 = rf(ctx, userID, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkAsRead provides a mock function with given fields: ctx, id, userID
func (_m *NotificationService) MarkAsRead(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClearAll provides a mock function with given fields: ctx, userID
func (_m *NotificationService) ClearAll(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationService creates a new instance of NotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationService {
	mock := &NotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
